#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""Content realization for multi-document text summarization that generates well-formed sentences."""

__author__ = "Amina Venton"
__email__ = "aventon@uw.edu"

def realize_content(topics_with_summaries_in_order):
    """
    This function takes in a list of Topics with chronologically ordered summaries
    generated by order_info(topics_with_summaries) in text_summarizer.py main.
    It should do sentence clean-up to generate well-formed sentences.
    """

    # for now return original list of topics
    return topics_with_summaries_in_order
