#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""Content realization for multi-document text summarization that generates well-formed sentences."""

__author__ = "Amina Venton"
__email__ = "aventon@uw.edu"

def realize_content(summaries_in_order):
    """
    This function takes in dictionary of {topic_id: [sentences]}
    generated by order_info(summaries_sent) in text_summarizer.py main.
    It should do sentence clean-up to generate well-formed sentences.
    """
    # Copy of original dictionary
    summaries = summaries_in_order.copy()

    # for now return original summaries_in_order dict {topic_id: [sentences]}
    return summaries
