#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from operator import itemgetter

"""Information ordering for multi-document text summarization that orders sentences in chronological order"""

__author__ = "Amina Venton"
__email__ = "aventon@uw.edu"

def order_info(topic_summaries):
    """
    This function takes in dictionary of {topic_id: [(sentence, date)]}
    generated by select_content(doc_data) in text_summarizer.py main.
    
    It orders the sentences chronologically (latest date first) for each topic
    and returns a dictionary of {topic_id: [sentences]}
    """

    # Dictionary to store ordered sentences for each topic
    summaries_in_order = dict()

    # Sort original dates in order
    for topic in topic_summaries:
        sentences = topic_summaries[topic]
        sentences.sort(key=itemgetter(1), reverse=True)

        # Get only the sentence from each tuple
        sorted_sent = [sen_pair[0] for sen_pair in sentences]

        # Add sentence array for each topic to new dict
        summaries_in_order[topic] = sorted_sent
        
    # Return dictionary with ordered sentences {topic_id: [sentences]}
    return summaries_in_order
